version: '3'
services:
  backend:
    volumes:
    - .:/workspace:cached
  
  frontend:
    volumes:
    - .:/workspace:cached
  
  netshoot:
    image: nicolaka/netshoot
    command: sleep infinity
    networks:
      - default
      - network-1